### PR TITLE
Waiterbot compile fix

### PR DESCRIPTION
**Pull request by jihoonl**
also compatible with new app manager.

### CODE REVIEW

**Comment by bit-pirate** [comment]
@jihoonl Instead of making a controller package for each waiterbot type, could we extend the current waiterbot controller (modularise it if necessary)? All waiterbots share the same drive base and sensors. What are the reason to make specific packages?

**Comment by jihoonl** [comment]
It is necessary. It uses different message, and behaves in different way. For example, cafe controller uses cafe_msgs and ces version uses rocon_demo_msgs.

Some libraries are sharable but not completely. If we starts to develop another demo with another msg format, the code will grow in ugly way.

Probably we can pull out code like navigator but I would not merge both controllers.

**Comment by bit-pirate** [comment]
OK, after discussing in person we decided to leave the waiterbot code as is. It requires a proper redesign, which will require a significant amount time. Hence, we will tackle it after the next demo.

Regarding this PR I'll merge it after Innorobo.

**Comment by bit-pirate** [comment]
Innorobo is done. Merging.

**Pull request merged**
